config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/todos', to: 'todos#new'
  get 'todos/new'
  post '/todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit',  as:'edit_todo'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy', as:'delete_todo'
  get 'todos/:id/complete', to: 'todos#complete', as:'complete_todo'
  get 'listaa', to:'todos#list', as:'list_todo'
  root 'todos#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
		@todos = Todo.all
	end

	 def new 
    	@todo = Todo.new
    end 


    def create
        todo = Todo.new(todo_params)
        if todo.save
        	redirect_to todo, notice: ' se creo correctamente la tarea'
        else
        	redirect_to todos_new_path, notice: ' no se pudo crear la tarea'
        end 
    end

       def show
    	@todo = Todo.find(params[:id])
    end

     def edit
    	@todo = Todo.find(params[:id])
    end

    def update
    	@todo = Todo.find(params[:id]) 
    	if @todo.update(todo_params)
    		redirect_to @todo, notice: 'El Post se ha actualizado con exito '
    	else
    		redirect_to edit_todo_path(@todo.id), notice: 'No se ha podido actualizar el registro'
    	end 
    end

        def destroy
        @todo = Todo.find(params[:id])
        @todo.destroy
        redirect_to root_path, notice: 'El Post se ha eliminado con exito '
       
    end

    def complete
    	@todo = Todo.find(params[:id])
        @todo.completed = true
        @todo.save
        redirect_to root_path
    end

    def list
    	@todos = Todo.all

    end 





    private

    def todo_params
    	params.require(:todo).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoAppp</title>
    <%= csrf_meta_tags %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"><%= link_to 'home', root_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"><%= link_to 'crear nueva tarea', todos_new_path %><span class="sr-only">(current)</span></a>
      </li>
           <li class="nav-item active">
        <a class="nav-link" href="#"><%= link_to 'ir a la lista', list_todo_path %><span class="sr-only">(current)</span></a>
      </li>

    </ul>
  </div>
</nav>
<br>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>Editando una Tarea</h1>

<%= form_with(model: @todo, local: true) do |form|%>

<%= form.label :descripción %>
<br><%= form.text_field :description %>
<br><%= form.submit 'actualizar'%>

<% end %>
<h2><%= link_to 'ir a los posts', root_path %></h2>

app/views/todos/index.html.erb
<h1><%= notice %></h1>
<br>
<div class="container">
  <div class="row">
    <div class="col-sm">
      <h3>No completados</h3>
      
          <% @todos.each do |todo|%>
        <div class="jumbotron">
           <% if todo.completed %>
          <%='completado' %>
          <% else %> 
          <%='no completado' %>
          <%end %>
          <h1 class="display-4"><%= todo.description%></h1>  
          <p class="lead">
            <button type="button" class="btn btn-success">
              <%= link_to 'Finalizar tarea', complete_todo_path(todo) %> 
            </button>
            <button id="1"type="button" class="btn btn-warning">
              <%= link_to 'Editar', edit_todo_path(todo) %>
            </button>
            <button type="button" class="btn btn-danger">
              <%= link_to 'Eliminar', delete_todo_path(todo), method: :delete %>
            </button></p> 
          </div>
          <% end %>
    </div>  
  </div>   
</div>




      

  

app/views/todos/list.html.erb
<h1><%= notice %></h1>
<br>
<div class="container">
  <div class="row">
    <div class="col-sm">
      
      <h3>No completados</h3>
          <% @todos.each do |todo|%>
      <% if !todo.completed %>
        <div class="jumbotron">
           <% if todo.completed %>
          <%='completado' %>
          <% else %> 
          <%='no completado' %>
          <%end %>
          <h1 class="display-4"><%= todo.description%></h1>  
        
          </div>
          <% end %>
        <% end %>
    </div>

     <div class="col-sm">
      <h3>completados</h3>
          <% @todos.each do |todo|%>
        <div class="jumbotron">
           <% if todo.completed %>
          <%='completado' %>
          <% else %> 
          <%='no completado' %>
          <%end %>
          <h1 class="display-4"><%= todo.description%></h1>  
          </div>
          <% end %>
    </div>   
  </div>   
</div>

app/views/todos/new.html.erb
<h1><%= notice %></h1>
<h2>Creación de una nueva tarea</h2>
<%= form_with(model: @todo, local: true) do |form|%>

<%= form.label :descripcion %>
<br><%= form.text_field :description %>
<br><%= form.submit 'Crear Tarea'%>
<% end %>

<br><%= link_to 'Volver al Index'%>
<h2><%= link_to 'ir a las Tareas', root_path %></h2>

app/views/todos/show.html.erb
<h3>Detalle del post</h3>
<p>
	<br><strong>Título: </strong><%= @todo.description%>
</p>

<h1><%= notice %></h1>